% TS_TYPE  Script to define classes of all TURBOSTREAM variables

% Attributes
a = {'nb' 'in'};

% Application variables
av = {'adaptive_smoothing' 'in'; 'cfl' 'fl'; 'cp' 'fl'; 'dampin' 'fl'; 'dts' 'in'; ...
    'dts_conv' 'fl'; 'fac_sa_smth' 'fl'; 'fac_sa_step' 'fl'; 'fac_st0' 'fl'; ...
    'fac_st1' 'fl'; 'fac_st2' 'fl'; 'fac_st3' 'fl'; 'fac_stmix' 'fl'; 'fac_wall' 'fl'; ...
    'facsafe' 'fl'; 'facsecin' 'fl'; 'frequency' 'fl'; 'ga' 'fl'; 'if_no_mg' 'in'; ...
    'ifgas' 'in'; 'ilos' 'in'; 'nchange' 'in'; 'ncycle' 'in'; 'nlos' 'in'; ...
    'nomatch_int' 'in'; 'nstep' 'in'; 'nstep_cycle' 'in'; 'nstep_inner' 'in'; ...
    'nstep_save' 'in'; 'nstep_save_probe' 'in'; 'nstep_save_start' 'in'; ...
    'nstep_save_start_probe' 'in'; 'poisson_cfl' 'fl'; 'poisson_nsmooth' 'in'; ...
    'poisson_nstep' 'in'; 'poisson_restart' 'in'; 'poisson_sfin' 'fl'; 'prandtl' 'fl'; ...
    'restart' 'in'; 'rfmix' 'fl'; 'rfvis' 'fl'; 'rg_cp0' 'fl'; 'rg_cp1' 'fl'; ...
    'rg_cp2' 'fl'; 'rg_cp3' 'fl'; 'rg_cp4' 'fl'; 'rg_cp5' 'fl'; 'rg_rgas' 'fl'; 'sfin' 'fl'; ...
    'turb_vis_damp' 'fl'; 'turbvis_lim' 'fl'; 'viscosity_a1' 'fl'; 'viscosity_a2' 'fl'; ...
    'viscosity_a3' 'fl'; 'viscosity_a4' 'fl'; 'viscosity_a5' 'fl'; 'viscosity' 'fl'; ...
    'viscosity_law' 'in'; 'wall_law' 'in'; 'write_force' 'in'; 'write_yplus' 'in' ; ...
    'write_tdamp' 'in' ; 'write_egen' 'in' ; 'ifsuperfac' 'in' ;  'poisson_limit' 'in' ;...
    'tref' 'fl' ; 'pref' 'fl' ; 'nspecies' 'in' ;...
    'sf_scalar' 'fl' ; 'schmidt_0' 'fl' ; 'schmidt_1' 'fl' ; 'cp0_0' 'fl' ; 'cp1_0' 'fl' ;...
    'cp2_0' 'fl' ; 'cp3_0' 'fl' ; 'cp4_0' 'fl' ; 'cp5_0' 'fl' ; 'rgas_0' 'fl' ; 'cp0_1' 'fl' ; ...
    'cp1_1' 'fl' ; 'cp2_1' 'fl' ; 'cp3_1' 'fl' ; 'cp4_1' 'fl' ; 'cp5_1' 'fl' ; 'rgas_1' 'fl' ; ...
    'cfl_ko' 'fl' ; 'cfl_st_ko' 'fl' ; 'cfl_en_ko' 'fl' ; 'sfin_sa' 'fl' ; 'sfin_ko' 'fl' ; ...
    'ko_dist' 'fl' ; 'ko_restart' 'in' ; 'fac_st0_option' 'in' ; 'sa_helicity_option' 'in' ; ...
    'sa_ch1' 'fl' ; 'sa_ch2' 'fl'};
    
% Block variables
bv = {'cfl_mul' 'fl' ; 'dampin_mul' 'fl' ; 'facsecin_mul' 'fl' ; 'fac_st0' 'fl'  ; 'fblade' 'fl' ;...
    'fmgrid' 'fl' ; 'fracann' 'fl' ; 'free_turb' 'fl' ; 'fsturb' 'fl' ; 'ftype' 'in' ;...
    'itrans' 'in' ; 'itrans_j1_en' 'in' ; 'itrans_j1_frac' 'fl' ; ...
    'itrans_j1_st' 'in' ; 'itrans_j2_en' 'in' ; 'itrans_j2_frac' 'fl' ; 'itrans_j2_st' 'in' ; ...
    'itrans_k1_en' 'in' ; 'itrans_k1_frac' 'fl' ; 'itrans_k1_st' 'in' ; 'itrans_k2_en' 'in' ; ...
    'itrans_k2_frac' 'fl' ; 'itrans_k2_st' 'in' ; 'jtrans' 'in' ; 'jtrans_i1_en' 'in' ; ...
    'jtrans_i1_frac' 'fl' ; 'jtrans_i1_st' 'in' ; 'jtrans_i2_en' 'in' ; 'jtrans_i2_frac' 'fl' ; ...
    'jtrans_i2_st' 'in' ; 'jtrans_k1_en' 'in' ; 'jtrans_k1_frac' 'fl' ; 'jtrans_k1_st' 'in' ; ...
    'jtrans_k2_en' 'in' ; 'jtrans_k2_frac' 'fl' ; 'jtrans_k2_st' 'in' ; 'ktrans' 'in' ; ...
    'ktrans_i1_en' 'in' ; 'ktrans_i1_frac' 'fl' ; 'ktrans_i1_st' 'in' ; 'ktrans_i2_en' 'in' ; ...
    'ktrans_i2_frac' 'fl' ; 'ktrans_i2_st' 'in' ; 'ktrans_j1_en' 'in' ; 'ktrans_j1_frac' 'fl' ; ...
    'ktrans_j1_st' 'in' ; 'ktrans_j2_en' 'in' ; 'ktrans_j2_frac' 'fl' ; 'ktrans_j2_st' 'in' ; ...
    'nblade' 'in' ; 'nimixl' 'in' ; 'dtrans_dyn_vis' 'fl' ; ...
    'poisson_fmgrid' 'fl' ; 'pstatin' 'fl' ; 'pstatout' 'fl' ; 'rpm' 'fl' ; 'rpmi1' 'fl' ;...
    'rpmi2' 'fl' ; 'rpmj1' 'fl' ; 'rpmj2' 'fl' ; 'rpmk1' 'fl' ; 'rpmk2' 'fl' ; 'sfin_mul' 'fl' ;...
    'srough_i0' 'fl' ; 'srough_i1' 'fl' ; 'srough_j0' 'fl' ; 'srough_j1' 'fl' ; 'srough_k0' 'fl' ;...
    'srough_k1' 'fl' ; 'superfac' 'fl' ; 'superstep' 'fl' ; 'tstagin' 'fl' ; 'tstagout' 'fl' ; ...
    'vgridin' 'fl' ; 'vgridout' 'fl' ;...
    'xllim' 'fl' ; 'xllim_free' 'fl' ; 'dro_avg' 'fl' ;  'dro_superfac' 'fl' ;...
    'droe_avg' 'fl' ;  'droe_superfac' 'fl' ;  'drorvt_avg' 'fl' ;  'drorvt_superfac' 'fl' ;...
    'drovr_avg' 'fl' ;  'drovr_superfac' 'fl' ;  'drovx_avg' 'fl' ;  'drovx_superfac' 'fl' ; ...
    'ndup_phaselag' 'in' ; 'turb_intensity' 'fl'};

% Block attributes
ba = {'np' 'in' ; 'nc' 'in'; 'ncl' 'in'; 'bid' 'in'; 'procid' 'in'; 'threadid' 'in'; 'ni' 'in';...
    'nj' 'in'; 'nk' 'in'};

% Connectivity attributes
ca = {'bid' 'in'; 'clid' 'in'; 'nxbid' 'in'; 'kind' 'in' ; 'n' 'in'};

% Connectivity variables
cl = {'ilist' 'in'; 'jlist' 'in'; 'klist' 'in'; 'nxilist' 'in'; 'nxjlist' 'in'; 'nxklist' 'in'};

% Cut attributes
ua = {'bid' 'in'; 'cid' 'in'; 'var_bpid' 'in'; 'var' 'fl'};

% Patch properties
pp = {'pstag' 'fl' ; 'tstag' 'fl'; 'yaw' 'fl'; 'pitch' 'fl'};% ; 'pout' 'fl'};

% Patch variables
pv = {'rfin' 'fl'; 'sfinlet' 'fl'; 'pout' 'fl'; 'ipout' 'in'; 'throttle_type' 'in';...
    'throttle_target' 'fl'; 'throttle_k0' 'fl'; 'throttle_k1' 'fl'; 'throttle_k2' 'fl' ;...
    'pout_en' 'fl' ; 'pout_st' 'fl' ; 'pout_nchange' 'in' ;...
    'pstagfixed' 'fl'; 'tstagfixed' 'fl'; 'vxfixed' 'fl'; 'vrfixed' 'fl'; 'vtfixed' 'fl' ;...
    'cool_type', 'in' ; 'cool_mass' , 'fl' ; 'cool_pstag' , 'fl'; 'cool_tstag', 'fl' ;...
    'cool_mach', 'fl' ; 'cool_frac_area', 'fl'; 'cool_sangle' 'fl'; 'cool_xangle', 'fl' ;...
    'bleed_flow', 'fl' ; 'probe_append', 'in'; 'slide_nxbid' 'in'; 'slide_nxpid' 'in' ;...
    'shroud_sealgap', 'fl' ; 'shroud_nseal', 'in' ; 'shroud_cfshroud', 'fl' ;...
    'shroud_cfcasing', 'fl' ; 'shroud_wshroud', 'fl' ; 'shroud_wcase', 'fl' ;...
    'shroud_pitchin', 'fl' ; 'shroud_dir', 'in' ; 'pstag_free' 'fl' ; 'tstag_free' 'fl' ;...
    'pstat_free' 'fl' ; 'sf_free' 'fl' ; 'group' 'in'};

% Patch attributes
pa = {'bid' 'in'; 'pid' 'in'; 'kind' 'in'; 'ist' 'in'; 'ien' 'in'; 'jst' 'in'; 'jen' 'in';...
    'kst' 'in'; 'ken' 'in'; 'idir' 'in'; 'jdir' 'in'; 'kdir' 'in'; 'nxbid' 'in'; 'nxpid' 'in';...
    'nface' 'in' ; 'nt' 'in'};


