%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/jordaneriksen/Documents/Uni/Part 2B/Project/Drone Control/STATIC_THRUST.txt
%
% Auto-generated by MATLAB on 31-Jan-2020 11:43:11

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["timethr", "THR"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("/Users/jordaneriksen/Documents/Uni/Part 2B/Project/Drone Control/STATIC_THRUST.txt", opts);

%% Convert to output type
timethr = tbl.timethr;
THR = tbl.THR;

%% Clear temporary variables
clear opts tbl