%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/jordaneriksen/Documents/Uni/Part 2B/Project/Drone Control/LC_cal.txt
%
% Auto-generated by MATLAB on 12-Feb-2020 09:53:05

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = "value";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
tbl = readtable("/Users/jordaneriksen/Documents/Uni/Part 2B/Project/Drone Control/LC_cal.txt", opts);

%% Convert to output type
value = tbl.value;

%% Clear temporary variables
clear opts tbl