function [fitresult, gof] = APC_RPM_THR(RPMAPC, ThrustAPC)
%CREATEFIT(RPM,THRUST1)
%  Create a fit.
%
%  Data for 'APC_RPM_THR' fit:
%      X Input : RPM
%      Y Output: Thrust1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Nov-2019 15:51:02


%% Fit: 'APC_RPM_THR'.
[xData, yData] = prepareCurveData( RPMAPC, ThrustAPC );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [1.88780012554911e-07 1.99727901774089];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
end


