function [RPMAPC, V5APC, JAPC, PeAPC, CtAPC, CpAPC, PWRAPC, TorqueAPC, ThrustAPC] = importAPC(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [RPMAPC, V5APC, JAPC, PE, CT, CP, PWRAPC, TORQUE, THRUST1] = IMPORTFILE(FILENAME)
%  reads data from text file FILENAME for the default selection.
%  Returns the data as column vectors.
%
%  [RPMAPC, V5APC, JAPC, PE, CT, CP, PWRAPC, TORQUE, THRUST1] = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [RPMAPC, V5APC, JAPC, PeAPC, CtAPC, CpAPC, PWRAPC, TorqueAPC, ThrustAPC] = importfile("/Users/jordaneriksen/Documents/Uni/Part 2B/Project/Drone Control/APCPROPDATA.txt", [4, 18]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-Nov-2019 15:51:57

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, 18];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["RPMAPC", "V5APC", "JAPC", "PeAPC", "CtAPC", "CpAPC", "PWRAPC", "TorqueAPC", "ThrustAPC"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
RPMAPC = tbl.RPMAPC;
V5APC = tbl.V5APC;
JAPC = tbl.JAPC;
PeAPC = tbl.PeAPC;
CtAPC = tbl.CtAPC;
CpAPC = tbl.CpAPC;
PWRAPC = tbl.PWRAPC;
TorqueAPC = tbl.TorqueAPC;
ThrustAPC = tbl.ThrustAPC;
end